# Generated by Django 3.2.7 on 2021-09-22 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_api_story_id', models.CharField(max_length=10, null=True, verbose_name='Story ID from the API')),
                ('story_type', models.CharField(max_length=15, null=True, verbose_name="Type of item One of 'job, 'story', 'comment', 'poll', or 'pollopt'")),
                ('author', models.CharField(max_length=50, null=True, verbose_name='Name of the author')),
                ('time', models.DateTimeField(null=True, verbose_name='Creation date of the item')),
                ('text', models.TextField(null=True, verbose_name='The comment, story or poll text.')),
                ('dead', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=550, null=True, verbose_name='The URL of the story.')),
                ('score', models.CharField(max_length=10, null=True, verbose_name="The story's score, or the votes for a pollopt.")),
                ('title', models.CharField(max_length=500, null=True, verbose_name='The title of the story, poll or job. HTML.')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_comment_api_id', models.CharField(max_length=10, null=True, verbose_name='Story ID from the API')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='Name of the author')),
                ('time', models.DateTimeField(null=True, verbose_name='Creation date of the item')),
                ('text', models.TextField(null=True, verbose_name='The comment, story or poll text.')),
                ('dead', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=550, null=True, verbose_name='The URL of the story.')),
                ('score', models.CharField(max_length=10, null=True, verbose_name="The story's score, or the votes for a pollopt.")),
                ('title', models.CharField(max_length=500, null=True, verbose_name='The title of the story, poll or job. HTML.')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.story')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
