# Generated by Django 3.2.7 on 2021-09-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateststory',
            name='slug',
            field=models.SlugField(max_length=2000, null=True),
        ),
    ]
