# Generated by Django 3.2.7 on 2021-09-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='url',
            new_name='comment_url',
        ),
        migrations.RenameField(
            model_name='lateststory',
            old_name='url',
            new_name='story_url',
        ),
    ]
